### ISSUE TITLE
add a list for links I don't want to test

### ISSUE THREAD

**Issue by Boshomi** [myshen/chrome-extension-linkchecker#1]
Please add a list where I can insert domains or keywords to ignore.

There is a really good Open Source Firefox-Addon http://evaluator.oclc.org/ with a configure form. The really good part is the "Don't test links that contain:" Field.

e.g.: If i want to test links in github, I would add "Sign out" into the ignore list, so i don't get logged out.
If i want to test only external links I would add "github.com"

btw.: This tool could be the best replacement for the Firefox-Tool it in Chrome.

**Comment by myshen** [comment]
@Boshomi this should be added in v2.0.0 under Options.
